@extends('layouts.app')

@section('content')
    @include('partials.hero')
    @include('partials.esencia')
    @include('partials.residencias')
    @include('partials.interiores')
    @include('partials.cta-video')
    @include('partials.amenidades')
    @include('partials.galeria')
    @include('partials.masterplan')
    @include('partials.ubicacion')
    @include('partials.mapa')
    @include('partials.respaldo')
    @include('partials.financiamiento')
    @include('partials.contacto')
@endsection
